package de.samply.notification;

public enum OperationType {
    CHECK_SEND_QUERY,
    CHECK_SEND_AND_EXECUTE_QUERY,
    SEND_QUERY_TO_BRIDGEHEAD_AND_EXECUTE,
    SEND_QUERY_TO_BRIDGEHEAD,
    CREATE_DATASHIELD_TOKEN,
    REFRESH_DATASHIELD_TOKEN,
    REMOVE_DATASHIELD_TOKEN,
    REMOVE_DATASHIELD_TOKENS_AND_PROJECT,
    CHANGE_PROJECT_STATE,
    ASSIGN_USER_TO_PROJECT,
    CHANGE_PROJECT_BRIDGEHEAD_USER_EVALUATION,
    CHANGE_PROJECT_BRIDGEHEAD_STATE,
    EDIT_QUERY,
    ADD_DOCUMENT,
    EDIT_PROJECT,
    SEND_EMAIL,
    CREATE_CODER_WORKSPACE,
    DELETE_CODER_WORKSPACE,
    TRANSFER_FILE_TO_CODER,
    REGISTER_IN_APP_REGISTER,
    UNREGISTER_IN_APP_REGISTER,
    TRANSFER_FILES_TO_RESEARCH_ENVIRONMENT
}
