package de.samply.notification;

public enum OperationType {
    SEND_QUERY_TO_BRIDGEHEAD_AND_EXECUTE,
    SEND_QUERY_TO_BRIDGEHEAD,
    CREATE_DATASHIELD_TOKEN,
    REFRESH_DATASHIELD_TOKEN,
    REMOVE_DATASHIELD_TOKEN,
    REMOVE_DATASHIELD_TOKENS_AND_PROJECT,
    CHANGE_PROJECT_STATE,
    ASSIGN_USER_TO_PROJECT,
    CHANGE_PROJECT_BRIDGEHEAD_USER_EVALUATION,
    CHANGE_PROJECT_BRIDGEHEAD_STATE,
    EDIT_QUERY,
    ADD_DOCUMENT,
    EDIT_PROJECT,
    SEND_EMAIL
}
