package de.samply.email;

public enum EmailTemplateType {
    INVITATION,
    NEW_PROJECT,
    FINISHED_PROJECT,
    PROJECT_REJECTED,
    PROJECT_BRIDGEHEAD_ACCEPTED,
    PROJECT_BRIDGEHEAD_REJECTED,
    SCRIPT_ACCEPTED,
    SCRIPT_REJECTED,
    REQUEST_CHANGES_IN_SCRIPT,
    NEW_TOKEN_FOR_AUTHENTICATION_SCRIPT,
    INVALID_AUTHENTICATION_SCRIPT,
    RESULTS_ACCEPTED,
    RESULTS_REJECTED,
    REQUEST_CHANGES_IN_PROJECT,
    ANALYSIS_ACCEPTED,
    ANALYSIS_REJECTED,
    REQUEST_CHANGES_IN_PROJECT_ANALYSIS,
    NEW_PROJECT_ACCEPTED,
    NEW_VOTUM,
    REQUEST_TECHNICAL_APPROVAL,
    NEW_PUBLICATION
}
