package de.samply.email;

public enum EmailRecipientType {
    SESSION_USER,
    EMAIL_ANNOTATION,
    CREATOR,
    PROJECT_MANAGER_ADMIN,
    ALL_DEVELOPERS,
    ALL_PILOTS,
    ALL_FINALS,
    ALL_BRIDGEHEAD_ADMINS,
    BRIDGEHEAD_ADMIN,
    BRIDGHEAD_ADMINS_WHO_HAVE_NOT_ACCEPTED_NOR_REJECTED_THE_PROJECT,
    PROJECT_ALL
}
