package de.samply.email;

public enum EmailRecipientType {
    SESSION_USER,
    EMAIL_ANNOTATION,
    PROJECT_MANAGER_ADMIN,
    BRIDGEHEAD_ADMIN,
    BRIDGHEAD_ADMINS_WHO_HAVE_NOT_ACCEPTED_NOR_REJECTED_THE_PROJECT,
    PROJECT_ALL
}
